import { Test, TestingModule } from '@nestjs/testing';
import { ConfigService } from '@nestjs/config';
import { promises as fs } from 'fs';
import * as os from 'os';
import * as path from 'path';
import { STORAGE_S3_CLIENT_FACTORY } from './storage.constants';
import { StorageService } from './storage.service';

describe('StorageService', () => {
  let service: StorageService;
  let configService: { get: jest.Mock };

  beforeEach(async () => {
    configService = {
      get: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        StorageService,
        { provide: ConfigService, useValue: configService },
        {
          provide: STORAGE_S3_CLIENT_FACTORY,
          useValue: jest.fn(),
        },
      ],
    }).compile();

    service = module.get<StorageService>(StorageService);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('uploads to S3 when AWS credentials are configured', async () => {
    const upload = jest.fn().mockReturnValue({
      promise: jest
        .fn()
        .mockResolvedValue({ Location: 'https://bucket.s3.amazonaws.com/a.png' }),
    });
    const deleteObject = jest.fn();
    const s3Factory = jest.fn().mockImplementation(() => ({
      upload,
      deleteObject,
    }));

    configService.get.mockImplementation((key: string) => {
      const values: Record<string, string> = {
        AWS_ACCESS_KEY_ID: 'key',
        AWS_SECRET_ACCESS_KEY: 'secret',
        AWS_REGION: 'eu-west-1',
        AWS_S3_BUCKET: 'bucket',
      };
      return values[key];
    });

    const moduleRef = await Test.createTestingModule({
      providers: [
        StorageService,
        { provide: ConfigService, useValue: configService },
        { provide: STORAGE_S3_CLIENT_FACTORY, useValue: s3Factory },
      ],
    }).compile();

    service = moduleRef.get(StorageService);

    const url = await service.uploadFile(Buffer.from('avatar'), 'avatar.png');

    expect(s3Factory).toHaveBeenCalledWith({
      region: 'eu-west-1',
      accessKeyId: 'key',
      secretAccessKey: 'secret',
    });
    expect(upload).toHaveBeenCalledWith(
      expect.objectContaining({
        Bucket: 'bucket',
        Body: expect.any(Buffer),
        ACL: 'public-read',
      }),
    );
    expect(url).toBe('https://bucket.s3.amazonaws.com/a.png');
  });

  it('falls back to local storage when AWS configuration is missing', async () => {
    const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'storage-service-'));

    configService.get.mockImplementation((key: string) => {
      const values: Record<string, string> = {
        STORAGE_LOCAL_DIR: tempDir,
        APP_URL: 'http://localhost:3000',
      };
      return values[key];
    });

    const url = await service.uploadFile(Buffer.from('hello'), 'photo.png');

    expect(url).toMatch(/^http:\/\/localhost:3000\/uploads\/.+-photo\.png$/);

    const storedFilename = url.split('/').pop();
    const storedContent = await fs.readFile(path.join(tempDir, storedFilename!));
    expect(storedContent.toString()).toBe('hello');
  });

  it('deletes local files generated by the fallback storage', async () => {
    const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'storage-delete-'));

    configService.get.mockImplementation((key: string) => {
      const values: Record<string, string> = {
        STORAGE_LOCAL_DIR: tempDir,
        APP_URL: 'http://localhost:3000',
      };
      return values[key];
    });

    const url = await service.uploadFile(Buffer.from('hello'), 'photo.png');
    const storedFilename = url.split('/').pop()!;
    const filePath = path.join(tempDir, storedFilename);

    await expect(fs.access(filePath)).resolves.toBeUndefined();
    await service.deleteFile(url);
    await expect(fs.access(filePath)).rejects.toThrow();
  });
}
